### ISSUE TITLE
restberry.com

### ISSUE THREAD

**Issue by enten** [materik/restberry#15]
There is a problem with the domain restberry.com: it's unreachable.

**Comment by materik** [comment]
Thanks a lot!!!!! Have to rebuy the domain :sweat_smile:

**Comment by materik** [comment]
:white_check_mark: Done... will take a couple of minutes for it to go up! Thanks again :+1:

**Comment by enten** [comment]
You're welcome.

**Comment by pantchox** [comment]
Offline again

**Comment by materik** [comment]
the domain is done. the new url is https://restberry-1c297.firebaseapp.com
