### ISSUE TITLE
Return full objects from .addReadManyRoute()

### ISSUE THREAD

**Issue by petarslovic** [materik/restberry#16]
Is it possible to have the .addReadManyRoute() return full objects?
I ran the example, created a few Cities, and added .addReadManyRoute() to the City model.

When I open `/api/v1/cities`, this is returned (even though those cities have a name and location properties):

````
{
  hrefs: {
    current: "/api/v1/cities?offset=0&limit=10",
    first: null,
    next: null,
    prev: null,
    last: null
  },
  offset: 0,
  limit: 10,
  total: 2,
  cities: [
    {
      href: "/api/v1/cities/56df653d8e6466c730803693",
      id: "56df653d8e6466c730803693"
    },
    {
      href: "/api/v1/cities/56df6581ad47d6f230a8e779",
      id: "56df6581ad47d6f230a8e779"
    }
  ]
}
````

**Comment by materik** [comment]
you have to add `expand` to the query: `/api/v1/cities?expand=city`

**Comment by petarslovic** [comment]
Oh cool thanks! Didn't see it in the docs. Are there some other special query params like that?

**Comment by materik** [comment]
yeah.. I noticed that too that I hadn't documented that very well... you can use `fields` to just return certain fields in the response.. that should be it.

**Comment by petarslovic** [comment]
That sounds great, thanks :)

**Comment by materik** [comment]
:+1: I will update the documentation a bit.. thanks for the feedback :smile:
