### ISSUE TITLE
Choose fields return

### ISSUE THREAD

**Issue by lobor** [materik/restberry#3]
Hi,

I try to return id and other field of my model when call addReadManyRoute().
I don't find the options, or the way for this.

May be is not exist

**Comment by materik** [comment]
it's automatically supported. query the route with GET /your/path?fields=id,field1,field2

**Comment by materik** [comment]
if you mean that you never want to return a field you can set hidden=true in your mongoose schema,
ex: ```field3: {type: String, hidden: true}```

**Comment by lobor** [comment]
Thanks this work !

**Comment by materik** [comment]
@lobor which solution solved you problem? just curious :) let me know if you have any other issues

**Comment by lobor** [comment]
@materik yes, it solved my problem.
May be an other question.
I a have 2 models, SCI and ASSOCIE.
in SCI i have an array with all id of ASSOCIE difined, and on ASSOCIE just one id of SCI.
When i create a SCI, i defined several ASSOCIE on same time, and send all data on method POST. The SCI is creating, but not ASSOCIE. It's possible with your route or i should create a custom route ?

Schema SCI:
```javascript
{
        associes:[{
            type: restberry.odm.ObjectId,
            ref: 'Associe'
        }]
    }
```

schema ASSOCIE:
```javascript
{
        sci : {
            type: restberry.odm.ObjectId,
            ref: 'Sci'
        }
}
```

**Comment by materik** [comment]
first, i would probably not store the Associe ids in sci and just have a reference to sci in associe. you can always get all associes of a sci by querying the associates model with a find query. otherwise you will need to keep the data up to date in both objects.
